# Project: SkobanMM
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = SkobanMM_private.res
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows lib/libaldat.a lib/liballd.a lib/liballd_s.a lib/liballeg.a lib/liballeg_s.a lib/liballp.a lib/liballp_s.a  
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Users/Björn/Dropbox/Programmierung/Programme_C++/Skoban Mapmaker/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/Users/Björn/Dropbox/Programmierung/Programme_C++/Skoban Mapmaker/include" 
BIN  = SkobanMM.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before SkobanMM.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "SkobanMM.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

SkobanMM_private.res: SkobanMM_private.rc 
	$(WINDRES) -i SkobanMM_private.rc --input-format=rc -o SkobanMM_private.res -O coff 
